export const steps = [
  {
    title: 'Manage Your Entire Production',
    description:
      'Manage schedules, sets, locations, budgets, crew, vendors, orders and documents-all from one app.',
    image:
      'https://images.pexels.com/photos/5488369/pexels-photo-5488369.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2',
  },
  {
    title: 'Easily Find and Hire Vendors',
    description:
      'Request and order rentals, services and products from trusted vendors in just a few taps.',
    image:
      'https://images.pexels.com/photos/9685238/pexels-photo-9685238.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2',
  },
  {
    title: 'Stay on Budget in Real Time',
    description:
      'Track real-time costs and budget changes with live updates from all departments.',
    image:
      'https://images.pexels.com/photos/8089652/pexels-photo-8089652.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2',
  },
  {
    title: 'Approve Payments with Confidence',
    description:
      'Approve vendor payments and manage P-cards directly in the app, fast and secure.',
    image:
      'https://images.pexels.com/photos/9685238/pexels-photo-9685238.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2',
  },
  {
    title: 'Track Deliveries in Real-Time',
    description:
      'Track Deliveries as They Happen and communicate accurate drop-off locations and change requests.',
    image:
      'https://images.pexels.com/photos/2272839/pexels-photo-2272839.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2',
  },
  {
    title: 'Keep Your Team Connected',
    description:
      'Chat with crew, vendors, and departments instantly, keeping everyone on the same page.',
    image:
      'https://images.pexels.com/photos/7688156/pexels-photo-7688156.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2',
  },
  {
    title: 'Stay Informed with Alerts',
    description:
      'Receive personal production-wide and emergency notifications to keep everyone updated.',
    image:
      'https://images.pexels.com/photos/3747481/pexels-photo-3747481.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2',
  },
  {
    title: 'Safety and Security Made Easy',
    description:
      'Acces expert security personnel and safety advisors, and manage incident reports seamlessly.',
    image:
      'https://images.pexels.com/photos/5380655/pexels-photo-5380655.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2',
  },
  {
    title: 'Lorem Ispum is dummy text',
    description:
      'Lorem Ipsum is simply dummy text of the printing and typesetting industry.',
    image:
      'https://images.pexels.com/photos/5488369/pexels-photo-5488369.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2',
  },
];

export const countries = [
  {name: 'Afghanistan', flag: '🇦🇫', callingCode: '+93'},
  {name: 'Albania', flag: '🇦🇱', callingCode: '+355'},
  {name: 'Algeria', flag: '🇩🇿', callingCode: '+213'},
  {name: 'Andorra', flag: '🇦🇩', callingCode: '+376'},
  {name: 'Angola', flag: '🇦🇴', callingCode: '+244'},
  {name: 'Antigua and Barbuda', flag: '🇦🇬', callingCode: '+1-268'},
  {name: 'Argentina', flag: '🇦🇷', callingCode: '+54'},
  {name: 'Armenia', flag: '🇦🇲', callingCode: '+374'},
  {name: 'Australia', flag: '🇦🇺', callingCode: '+61'},
  {name: 'Austria', flag: '🇦🇹', callingCode: '+43'},
  {name: 'Azerbaijan', flag: '🇦🇿', callingCode: '+994'},
  {name: 'Bahamas', flag: '🇧🇸', callingCode: '+1-242'},
  {name: 'Bahrain', flag: '🇧🇭', callingCode: '+973'},
  {name: 'Bangladesh', flag: '🇧🇩', callingCode: '+880'},
  {name: 'Barbados', flag: '🇧🇧', callingCode: '+1-246'},
  {name: 'Belarus', flag: '🇧🇾', callingCode: '+375'},
  {name: 'Belgium', flag: '🇧🇪', callingCode: '+32'},
  {name: 'Belize', flag: '🇧🇿', callingCode: '+501'},
  {name: 'Benin', flag: '🇧🇯', callingCode: '+229'},
  {name: 'Bhutan', flag: '🇧🇹', callingCode: '+975'},
  {name: 'Bolivia', flag: '🇧🇴', callingCode: '+591'},
  {name: 'Bosnia and Herzegovina', flag: '🇧🇦', callingCode: '+387'},
  {name: 'Botswana', flag: '🇧🇼', callingCode: '+267'},
  {name: 'Brazil', flag: '🇧🇷', callingCode: '+55'},
  {name: 'Brunei', flag: '🇧🇳', callingCode: '+673'},
  {name: 'Bulgaria', flag: '🇧🇬', callingCode: '+359'},
  {name: 'Burkina Faso', flag: '🇧🇫', callingCode: '+226'},
  {name: 'Burundi', flag: '🇧🇮', callingCode: '+257'},
  {name: 'Cabo Verde', flag: '🇨🇻', callingCode: '+238'},
  {name: 'Cambodia', flag: '🇰🇭', callingCode: '+855'},
  {name: 'Cameroon', flag: '🇨🇲', callingCode: '+237'},
  {name: 'Canada', flag: '🇨🇦', callingCode: '+1'},
];


// export const countries = [
//   { name: "Afghanistan", flag: "🇦🇫", callingCode: "+93" },
//   { name: "Albania", flag: "🇦🇱", callingCode: "+355" },
//   { name: "Algeria", flag: "🇩🇿", callingCode: "+213" },
//   { name: "Andorra", flag: "🇦🇩", callingCode: "+376" },
//   { name: "Angola", flag: "🇦🇴", callingCode: "+244" },
//   { name: "Antigua and Barbuda", flag: "🇦🇬", callingCode: "+1-268" },
//   { name: "Argentina", flag: "🇦🇷", callingCode: "+54" },
//   { name: "Armenia", flag: "🇦🇲", callingCode: "+374" },
//   { name: "Australia", flag: "🇦🇺", callingCode: "+61" },
//   { name: "Austria", flag: "🇦🇹", callingCode: "+43" },
//   { name: "Azerbaijan", flag: "🇦🇿", callingCode: "+994" },
//   { name: "Bahamas", flag: "🇧🇸", callingCode: "+1-242" },
//   { name: "Bahrain", flag: "🇧🇭", callingCode: "+973" },
//   { name: "Bangladesh", flag: "🇧🇩", callingCode: "+880" },
//   { name: "Barbados", flag: "🇧🇧", callingCode: "+1-246" },
//   { name: "Belarus", flag: "🇧🇾", callingCode: "+375" },
//   { name: "Belgium", flag: "🇧🇪", callingCode: "+32" },
//   { name: "Belize", flag: "🇧🇿", callingCode: "+501" },
//   { name: "Benin", flag: "🇧🇯", callingCode: "+229" },
//   { name: "Bhutan", flag: "🇧🇹", callingCode: "+975" },
//   { name: "Bolivia", flag: "🇧🇴", callingCode: "+591" },
//   { name: "Bosnia and Herzegovina", flag: "🇧🇦", callingCode: "+387" },
//   { name: "Botswana", flag: "🇧🇼", callingCode: "+267" },
//   { name: "Brazil", flag: "🇧🇷", callingCode: "+55" },
//   { name: "Brunei", flag: "🇧🇳", callingCode: "+673" },
//   { name: "Bulgaria", flag: "🇧🇬", callingCode: "+359" },
//   { name: "Burkina Faso", flag: "🇧🇫", callingCode: "+226" },
//   { name: "Burundi", flag: "🇧🇮", callingCode: "+257" },
//   { name: "Cabo Verde", flag: "🇨🇻", callingCode: "+238" },
//   { name: "Cambodia", flag: "🇰🇭", callingCode: "+855" },
//   { name: "Cameroon", flag: "🇨🇲", callingCode: "+237" },
//   { name: "Canada", flag: "🇨🇦", callingCode: "+1" },
//   { name: "Chile", flag: "🇨🇱", callingCode: "+56" },
//   { name: "China", flag: "🇨🇳", callingCode: "+86" },
//   { name: "Colombia", flag: "🇨🇴", callingCode: "+57" },
//   { name: "Congo", flag: "🇨🇬", callingCode: "+242" },
//   { name: "Costa Rica", flag: "🇨🇷", callingCode: "+506" },
//   { name: "Croatia", flag: "🇭🇷", callingCode: "+385" },
//   { name: "Cuba", flag: "🇨🇺", callingCode: "+53" },
//   { name: "Cyprus", flag: "🇨🇾", callingCode: "+357" },
//   { name: "Czech Republic", flag: "🇨🇿", callingCode: "+420" },
//   { name: "Denmark", flag: "🇩🇰", callingCode: "+45" },
//   { name: "Djibouti", flag: "🇩🇯", callingCode: "+253" },
//   { name: "Dominica", flag: "🇩🇲", callingCode: "+1-767" },
//   { name: "Dominican Republic", flag: "🇩🇴", callingCode: "+1-809" },
//   { name: "Ecuador", flag: "🇪🇨", callingCode: "+593" },
//   { name: "Egypt", flag: "🇪🇬", callingCode: "+20" },
//   { name: "El Salvador", flag: "🇸🇻", callingCode: "+503" },
//   { name: "Estonia", flag: "🇪🇪", callingCode: "+372" },
//   { name: "Eswatini", flag: "🇸🇿", callingCode: "+268" },
//   { name: "Ethiopia", flag: "🇪🇹", callingCode: "+251" },
//   { name: "Finland", flag: "🇫🇮", callingCode: "+358" },
//   { name: "France", flag: "🇫🇷", callingCode: "+33" },
//   { name: "Georgia", flag: "🇬🇪", callingCode: "+995" },
//   { name: "Germany", flag: "🇩🇪", callingCode: "+49" },
//   { name: "Ghana", flag: "🇬🇭", callingCode: "+233" },
//   { name: "Greece", flag: "🇬🇷", callingCode: "+30" },
//   { name: "Greenland", flag: "🇬🇱", callingCode: "+299" },
//   { name: "Guatemala", flag: "🇬🇹", callingCode: "+502" },
//   { name: "Guyana", flag: "🇬🇾", callingCode: "+592" },
//   { name: "Haiti", flag: "🇭🇹", callingCode: "+509" },
//   { name: "Honduras", flag: "🇭🇳", callingCode: "+504" },
//   { name: "Hungary", flag: "🇭🇺", callingCode: "+36" },
//   { name: "Iceland", flag: "🇮🇸", callingCode: "+354" },
//   { name: "India", flag: "🇮🇳", callingCode: "+91" },
//   { name: "Indonesia", flag: "🇮🇩", callingCode: "+62" },
//   { name: "Iran", flag: "🇮🇷", callingCode: "+98" },
//   { name: "Iraq", flag: "🇮🇶", callingCode: "+964" },
//   { name: "Ireland", flag: "🇮🇪", callingCode: "+353" },
//   { name: "Israel", flag: "🇮🇱", callingCode: "+972" },
//   { name: "Italy", flag: "🇮🇹", callingCode: "+39" },
//   { name: "Jamaica", flag: "🇯🇲", callingCode: "+1-876" },
//   { name: "Japan", flag: "🇯🇵", callingCode: "+81" },
//   { name: "Jordan", flag: "🇯🇴", callingCode: "+962" },
//   { name: "Kazakhstan", flag: "🇰🇿", callingCode: "+7" },
//   { name: "Kenya", flag: "🇰🇪", callingCode: "+254" },
//   { name: "Kiribati", flag: "🇰🇮", callingCode: "+686" },
//   { name: "Kuwait", flag: "🇰🇼", callingCode: "+965" },
//   { name: "Kyrgyzstan", flag: "🇰🇬", callingCode: "+996" },
//   { name: "Laos", flag: "🇱🇦", callingCode: "+856" },
//   { name: "Latvia", flag: "🇱🇻", callingCode: "+371" },
//   { name: "Lebanon", flag: "🇱🇧", callingCode: "+961" },
//   { name: "Lesotho", flag: "🇱🇸", callingCode: "+266" },
//   { name: "Liberia", flag: "🇱🇷", callingCode: "+231" },
//   { name: "Libya", flag: "🇱🇾", callingCode: "+218" },
//   { name: "Lithuania", flag: "🇱🇹", callingCode: "+370" },
// ]