const Icons = {
  telephone: require('../assets/icons/telephone.png'),
  back: require('../assets/icons/back.png'),
  user: require('../assets/icons/user.png'),
  email: require('../assets/icons/email.png'),
  checked: require('../assets/icons/checked.png'),
  unchecked: require('../assets/icons/unchecked.png'),
  search: require('../assets/icons/search.png'),
  account: require('../assets/icons/account.png'),
  add: require('../assets/icons/add.png'),
  gallery: require('../assets/icons/gallery2.png'),
  camera: require('../assets/icons/camera.png'),
  delete: require('../assets/icons/trash.png'),
  calendar: require('../assets/icons/calendar.png'),
  person: require('../assets/icons/profile.png'),
  googleMaps: require('../assets/icons/google-maps.png'),
  close: require('../assets/icons/close.png'),
  location: require('../assets/icons/location.png'),
  eye: require('../assets/icons/eye.png'),
  eye_off: require('../assets/icons/eye-off.png'),
  birthday: require('../assets/icons/birthday.png'),
  lock: require('../assets/icons/accountPrivacy.png'),
  google: require('../assets/icons/google.png'),
  facebook: require('../assets/icons/facebook.png'),
  dashboard: require('../assets/icons/dashboard.png'),
  trip: require('../assets/icons/trip.png'),
  delivery: require('../assets/icons/delivery.png'),
  order: require('../assets/icons/order.png'),
  more: require('../assets/icons/menu.png'),
  settings: require('../assets/icons/settings.png'),
  accountDark: require('../assets/icons/accountDark.png'),
  right: require('../assets/icons/right-arrow.png'),
  chat: require('../assets/icons/chat.png'),
  newMsg: require('../assets/icons/newMsg.png'),
  bottomArrow: require('../assets/icons/bottomArrow.png'),
  video: require('../assets/icons/video.png'),
  chatGallery: require('../assets/icons/chatGallery.png'),
  share: require('../assets/icons/share.png'),
  mic: require('../assets/icons/mic.png'),
  emoji1: require('../assets/icons/emoji1.png'),
  emoji2: require('../assets/icons/emoji2.png'),
  emoji3: require('../assets/icons/emoji3.png'),
  emoji4: require('../assets/icons/emoji4.png'),
  emoji5: require('../assets/icons/emoji5.png'),
  reply: require('../assets/icons/reply.png'),
  forward: require('../assets/icons/forward.png'),
  group: require('../assets/icons/groupChat.png'),
  createGroup: require('../assets/icons/createGroup.png'),
  newChat: require('../assets/icons/newChat.png'),
  dots: require('../assets/icons/3dots.png'),
};

const Images = {
  dashboardImage: require('../assets/images/dashboardImage.png'),
  noInternet: require('../assets/images/noInternet.png'),
  splash: require('../assets/icons/splash.png'),
};
export {Images, Icons};
